### ISSUE TITLE
Casting bug in `results_regression` function

### ISSUE THREAD

**Issue by Yuxinya** [CompRhys/roost#13]
Error when running _ on windows machine.

```bash
 File "C:\Users\DELL\roost\examples\roost\utils.py", line 338, in results_regression
    pred = normalizer.denorm(output.data.cpu())
AttributeError: 'memoryview' object has no attribute 'cpu'
```

**Comment by Yuxinya** [comment]
File "C:\Users\DELL\roost\examples\roost\utils.py", line 338, in results_regression
    pred = normalizer.denorm(output.data.cpu())
AttributeError: 'memoryview' object has no attribute 'cpu'

**Comment by Yuxinya** [comment]
the bug in uitils "pred = normalizer.denorm(output.data.cpu())"

**Comment by CompRhys** [comment]
Edited issue for clarity. Will have a look but I believe this might be a Windows specific bug in which case I am not well placed to fix it.

**Comment by Yuxinya** [comment]
ok，thank you very much

**Comment by usccolumbia** [comment]
same issue on ubuntu linux:
  File "./roost/roost/core.py", line 246, in predict
    torch.cat(test_output, dim=0).view(-1).numpy(),
TypeError: can't convert cuda:1 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first

i changed this to:
    torch.cat(test_output, dim=0).view(-1).cpu().numpy(),

then it reports the above error.
pred = normalizer.denorm(output.data.cpu())
AttributeError: 'memoryview' object has no attribute 'cpu'

so I removed .cpu()
pred = normalizer.denorm(output.data)

now it has another error:
  File "roost/roost/core.py", line 359, in denorm
    return normed_tensor * self.std + self.mean
TypeError: unsupported operand type(s) for *: 'memoryview' and 'Tensor'

**Comment by usccolumbia** [comment]
> Error when running _ on windows machine.
> 
> ```shell
>  File "C:\Users\DELL\roost\examples\roost\utils.py", line 338, in results_regression
>     pred = normalizer.denorm(output.data.cpu())
> AttributeError: 'memoryview' object has no attribute 'cpu'
> ```

just change to:
    pred = normalizer.denorm(output.data)

**Comment by Yuxinya** [comment]
> > Error when running _ on windows machine.
> > ```shell
> >  File "C:\Users\DELL\roost\examples\roost\utils.py", line 338, in results_regression
> >     pred = normalizer.denorm(output.data.cpu())
> > AttributeError: 'memoryview' object has no attribute 'cpu'
> > ```
> 
> just change to:
> pred = normalizer.denorm(output.data)

it workes. thank you very very much

**Comment by Yuxinya** [comment]
> same issue on ubuntu linux:
> File "./roost/roost/core.py", line 246, in predict
> torch.cat(test_output, dim=0).view(-1).numpy(),
> TypeError: can't convert cuda:1 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first
> 
> i changed this to:
> torch.cat(test_output, dim=0).view(-1).cpu().numpy(),
> 
> then it reports the above error.
> pred = normalizer.denorm(output.data.cpu())
> AttributeError: 'memoryview' object has no attribute 'cpu'
> 
> so I removed .cpu()
> pred = normalizer.denorm(output.data)
> 
> now it has another error:
> File "roost/roost/core.py", line 359, in denorm
> return normed_tensor * self.std + self.mean
> TypeError: unsupported operand type(s) for *: 'memoryview' and 'Tensor'

and then i have the same problem on windows.
  File "examples/roost-example.py", line 485, in <module>
    main(**vars(args))
  File "examples/roost-example.py", line 203, in main
    eval_type="checkpoint",
  File "C:\Users\DELL\roost\examples\roost\utils.py", line 338, in results_regression
    pred = normalizer.denorm(output.data)
  File "C:\Users\DELL\roost\examples\roost\core.py", line 358, in denorm
    return normed_tensor * self.std + self.mean
TypeError: unsupported operand type(s) for *: 'memoryview' and 'Tensor'

**Comment by usccolumbia** [comment]
normed_tensor * self.std + self.mean

-->change  to:
torch.tensor(normed_tensor) * self.std + self.mean

**Comment by CompRhys** [comment]
@Yuxinya  @usccolumbia Hello, could you try pull the most recent change and see whether it now works. I did have a very minor difference between my local version which I overlooked pushing to remote. The change was reverting some device management changes to fix a slightly different bug after refactoring to make the `BaseModelClass` an ABC when running on GPU but that fix appears to resolve this issue on CPU also.

**Comment by CompRhys** [comment]
Please re-open if bug persists with the changes

**Comment by Yuxinya** [comment]
> normed_tensor * self.std + self.mean
> 
> -->change to:
> torch.tensor(normed_tensor) * self.std + self.mean

ok ,thank you for your all help, very thank you

**Comment by Yuxinya** [comment]
> Please re-open if bug persists with the changes
thank you for your help. but i am sorry , My computer is broken. if it repaired ,i would give you reply. thank you again for your time and help

**Comment by Yuxinya** [comment]
i use the way that provided on your github to install python3.6 ，torch and roost，it works. thanks very much for all helped me

**Comment by Yuxinya** [comment]
and my enviroment is win10 cpu
