### ISSUE TITLE
another bug in core.py  line 

### ISSUE THREAD

**Issue by usccolumbia** [CompRhys/roost#14]
def denorm(self, normed_tensor):
        return normed_tensor * self.std + self.mean

need to to conversion for normed_tensor.
-->
    def denorm(self, normed_tensor):
        return torch.tensor(normed_tensor) * self.std + self.mean

**Comment by CompRhys** [comment]
I believe this is also resolved with f19286c9b2d5dea32759112d57a1436886c401b4 - please re-open if not the case
