### ISSUE TITLE
Issue with TensorBoard summary writer on Windows Systems.

### ISSUE THREAD

**Issue by CompRhys** [CompRhys/roost#3]
Apparently when running `train.py` on Windows systems there is an issue with the TensorBoard summary writer (see lines 187-193).

```
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect
```

**Comment by K1423** [comment]
The error of Winerror 123 is solved by erasing the terms below in `train.py` that in lines187-193

 {date:%d-%m-%Y_%H:%M:%S} and date=datetime.datetime.now() .

![20200501221715](https://user-images.githubusercontent.com/60001617/80808048-a172e300-8bf9-11ea-813b-e41af10c93a0.png)
![20200501221737](https://user-images.githubusercontent.com/60001617/80808056-a46dd380-8bf9-11ea-820f-88d59da8ada3.png)
