### ISSUE TITLE
[Enhancement] Work out how to parallelise over multiple GPUs

### ISSUE THREAD

**Issue by CompRhys** [CompRhys/roost#6]
The easy option of using `nn.DataParallel` doesn't like the fact that we have tensors with variable dimensions along some axes due to the list of lists setup.

**Comment by CompRhys** [comment]
Can this be done using https://github.com/huggingface/accelerate?

**Comment by janosh** [comment]
Prob worth taking a closer look at https://pytorch-geometric.readthedocs.io/en/latest/notes/batching.html for this. They use diagonally stacked adjacency matrices which are sparsely stored to avoid memory overhead.

**Comment by CompRhys** [comment]
The list of lists I implemented is more general as we can have an atom B and an image atom B' in the environment of site A where they have different distances from A. This isn't able to be represented in the adjacency matrix setup. The challenges arise due to small unit cell periodic structures.

**Comment by janosh** [comment]
You closed as completed. Probably more accurate to close as not planned.
